/* WARNING: Do NOT edit this file.  It was created automatically
   with the command "make bibclean.h" by magsilva@discovery.ironiacorp.com
   in /home/magsilva/Projects/Projects-UTFPR/bibclean on Qua Ago 5 10:33:02 BRT 2015 */

	(const char*)NULL,
